### PR TITLE
Update install-debian

### PR DESCRIPTION
**Pull request by Tharadash**
Removed network-manager form line 170 in order to fix install issue:
https://forum.pine64.org/showthread.php?tid=8487&pid=90190#pid90190

### CODE REVIEW

**Comment by Tharadash** [comment]
I must add that I have absolutely no idea what this change will affect as well. 
I have not tested this change (yet) and am basing this on multiple forum posts as linked in the commit message.

**Comment by sirnewton01** [comment]
I'm going to give this patch a try because I ran into the same issue with policykit. Thanks for the PR!

**Comment by sirnewton01** [comment]
I managed to set up a fully functional Bullseye/GNOME/Wayland desktop environment with this patch. I didn't need to do anything special about the removed network manager. It seems to have been installed properly as part of the rest of the install process. Thank you.

**Comment by daniel-thompson** [comment]
Applied. Thanks!

**Pull request merged**
