### PR TITLE
add separate home partition.

### PR DESCRIPTION
**Pull request by xmixahlx**

### CODE REVIEW

**Comment by daniel-thompson** [comment]
Thanks for the patch but I'm afraid to say I'm not very keen on adding an unconditional home partition.

A home partition in a common habit, especially for people who change distros frequently, but it is certainly not a universally accepted best practice and it inevitably leads to juggling disk space since the root partition cannot be sized to please all use cases. As an example the Debian installer recommends a single partition approach for new users and for users who don't have a strong preference otherwise.

**Comment by xmixahlx** [comment]
understood. i thought of a variable usage, but always use a separate home myself.

**Comment by e-minguez** [comment]
I guess having a variable such as HOMESIZE=x , then if != null or 0, create such partition scheme, etc. otherwise keep it like today's.

**Comment by daniel-thompson** [comment]
I'd recommend sinking time into making the Debian installer come alive on PBP! Personally I think we're getting pretty close to the point when this installer can be deprecated:
https://github.com/daniel-thompson/pinebook-pro-debian-installer#roadmap

**Pull request closed without merging**
